<a href="https://colab.research.google.com/github/naugim26/2026-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3주차
# 단원 03 과학용 컴퓨팅 패키지
# numpy

### 51-61p제외

### 3.1 패키지 numpy 개요와 자료형 ndarray

In [ ]:
#ndarray
import numpy as np
a=np.array((2,3))
a

array([2, 3])

In [ ]:
import numpy as np
a=np.ndarray((3,2),dtype=int)
a

array([[      471253109,               0],
       [134185375044912,        11655696],
       [134184766986576,        10737088]])

In [ ]:
a=np.ndarray((3,2),int)
a

array([[      471253107,               0],
       [       11655552,        11653544],
       [134185395477936,        11656656]])

In [ ]:
# 내장함수 array()\
import numpy as np
a=np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)
# 최신환경에서 64비트 운영체제라 교재랑 다르게 나옴

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [ ]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np
unicode_array = np.array(['가나다','라마바','사아자'],dtype="<U32")
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'],dtype='U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

### 3.2 내장함수 arange()와 linspace()

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0,6.5))
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
#함수 linspace()
np.linspace(2.0,3.0)


array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0,3.0,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [ ]:
print((3-2)/(50-1))

0.02040816326530612


In [ ]:
np.linspace(2.0,3.0,endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [ ]:
print((3-2)/(50))

0.02


In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

In [ ]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)

### 3.3 내장함수 zeros()와 ones(),empty()

In [ ]:
# 내장함수 np.zeros()
import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b=np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
#원소가 모두 1.0인 배열을 생성하는 ones()
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#대각선 원소가 모두 1인 2차원 배열을 반환하는 함수
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#numpy.full
#fill_value로 shape모양의 배열을 반환하는 함수
import numpy as np
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [ ]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#배열을 생성하는
#numpy.empty(shape)
np.empty(3)
np.empty([2,2])
np.empty([2,3],dtype=int)

array([[          895203369,                   0, 7599296743584303730],
       [7070715622256175475, 2314885530454355823, 2322294337665396602]])

In [ ]:
#원소값이 0인 주어진 형태의 배열을 생성하는
#zeros_like(a)
a=np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#원소값이 1인 주어진 형태의 배열을 생성하는
#ones_like()
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#원소값이 주어진 값이며 주어진 형태의 배열을 생성하는
#full_like(a)
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### 3.4 배열 연산

In [ ]:
#배열과 스칼라와의 연산
import numpy as np
a=np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [ ]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b=np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [4]:
import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [5]:
b = np.arange(0.5,4,1)
b

array([0.5, 1.5, 2.5, 3.5])

In [6]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b+=a

In [7]:
# 2차원 배열의 곱 연산자 @
a = np.full((2,3),[1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [9]:
a @ b

array([[12,  6],
       [12,  6]])

In [10]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [11]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [12]:
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [13]:
a = np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [14]:
a.sum()

np.int64(46)

In [15]:
a.sum(axis=0)

array([16, 30])

In [16]:
a.sum(axis=1)

array([30, 13,  3])

In [17]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

46
[16 30]
[30 13  3]


In [18]:
a=np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [19]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [20]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [21]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [22]:
a=np.array([1,4,9])
a

array([1, 4, 9])

In [23]:
b=np.full_like(a,2)
b

array([2, 2, 2])

In [24]:
np.add(a,b)

array([ 3,  6, 11])

In [25]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [26]:
np.power(a,b)

array([ 1, 16, 81])

### 3.5배열 슬라이싱과 형태 수정



In [30]:
#1차원 배열의 첨자와 슬라이싱
import numpy as np
a=np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
a[3]

np.int64(9)

In [32]:
int(a[3])

9

In [ ]:
a[-2]

np.int64(64)

In [ ]:
a[1:4]

array([1, 4, 9])

In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
a[8:2:-2]

array([64, 36, 16])

In [35]:
a[::1]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
a[::-2]

array([81, 49, 25,  9,  1])

In [38]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [39]:
a[2:5] = [-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [40]:
a[2:5] = [-5,-5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [41]:
a[2:5]=-10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [45]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
#3차원 배열의 이해
a= np.arange(24).reshape(2,3,4)

In [44]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:,1,1]

array([ 5, 17])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1,...,1]

array([13, 17, 21])

In [ ]:
a[1,:,1]

array([13, 17, 21])

In [ ]:
a[0,...]

array([1, 2, 3])

In [ ]:
a[0]

array([1, 2, 3])

In [46]:
#3차원 배열의 이해
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
b=np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [50]:
np.transpose(b,(0,1,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [51]:
np.transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [52]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

### 3.6브로드캐스팅

In [53]:
a=np.array([3,4,5])
b=np.array([8,7,6])
a+b

array([11, 11, 11])

In [60]:
from numpy import arange
a=np.array([3,4,5,7])
b=np.array([8,7,6])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [61]:
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
y=arange(-1,2)
y

array([-1,  0,  1])

In [63]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [64]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [65]:
y=arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [66]:
np.set_printoptions(precision=2)

In [67]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [68]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [69]:
x = arange(1,4)
x

array([1, 2, 3])

In [70]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [71]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [72]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [73]:
x=arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [74]:
y=arange(1,3)
y

array([1, 2])

In [75]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [76]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [77]:
import numpy as np
from numpy import array
x=array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [78]:
np.newaxis is None

True

In [79]:
a=x[None, :]
a

array([[ 0, 10, 20, 30]])

In [80]:
a=x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [81]:
a=x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [82]:
a.shape

(4, 1)

In [83]:
a=x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [84]:
b = array([1,2,3])
b

array([1, 2, 3])

In [85]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [87]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### 3.7고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[1]]

array([1])

In [ ]:
x[[1,1,2,5]]

array([1, 1, 2, 5])

In [ ]:
x[[1,1,2,5,-1,-2,-5,-10]]

array([1, 1, 2, 5, 9, 8, 5, 0])

In [ ]:
x=np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[[5,6]]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[5,6]

np.int64(46)

In [ ]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[[0],[1]]

array([1])

In [ ]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:,[1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[:,[1,2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [ ]:
x[:,[2,1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[ [1,3] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[ [1,3],: ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1],[2] ]

array([10])

In [ ]:
x[ [1,3],[2,2] ]

array([10, 26])

In [ ]:
x[ [1],[2] ]

In [ ]:
x[ [1,3],[2,2,3] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
x[ [1,3],[2] ]

array([10, 26])

In [ ]:
x[ [1],[2] ]

array([10])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0,2,4],1]

array([ 1, 17, 33])

In [ ]:
x[[0,2,4,],:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[[0,2,4,],[0,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a=np.arange(40).reshape(5,8)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
np.arange(2,4)

array([2, 3])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2,4)] [ :, [1,0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,5)] [ :, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
np.arange(-1,-8,-1)

array([-1, -2, -3, -4, -5, -6, -7])

In [ ]:
a[np.arange(2,5)] [:,np.arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])