# 3주차
# 단원 03 과학용 컴퓨팅 패키지
# numpy

### 3.1 패키지 numpy 개요와 자료형 ndarray

In [1]:
#ndarray
import numpy as np
a=np.array((2,3))
a

array([2, 3])

In [2]:
import numpy as np
a=np.ndarray((3,2),dtype=int)
a

array([[      471253109,               0],
       [134185375044912,        11655696],
       [134184766986576,        10737088]])

In [3]:
a=np.ndarray((3,2),int)
a

array([[      471253107,               0],
       [       11655552,        11653544],
       [134185395477936,        11656656]])

In [8]:
# 내장함수 array()\
import numpy as np
a=np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [12]:
print(a.shape)
print(a.ndim)
print(a.dtype)
# 최신환경에서 64비트 운영체제라 교재랑 다르게 나옴

(3,)
1
int64


In [7]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [13]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [14]:
import numpy as np
unicode_array = np.array(['가나다','라마바','사아자'],dtype="<U32")
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [15]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'],dtype='U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

### 3.2 내장함수 arange()와 linspace()

In [16]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [17]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0,6.5))
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [18]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [21]:
#함수 linspace()
np.linspace(2.0,3.0)


array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [22]:
np.linspace(2.0,3.0,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [23]:
print((3-2)/(50-1))

0.02040816326530612


In [24]:
np.linspace(2.0,3.0,endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [26]:
print((3-2)/(50))

0.02


In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

In [ ]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)

### 3.3 내장함수 zeros()와 ones(),empty()

### 3.4 배열 연산

### 3.5배열 슬라이싱과 형태 수정



In [ ]:
#1차원 배열의 첨자와 슬라이싱
import numpy as np
a=np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[3]

np.int64(9)

In [ ]:
int(a[3])

9

In [ ]:
a[-2]

np.int64(64)

In [ ]:
a[1:4]

array([1, 4, 9])

In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
a[8:2:-2]

array([64, 36, 16])

In [ ]:
a= np.arange(24).reshape(2,3,4)

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:,1,1]

array([ 5, 17])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1,...,1]

array([13, 17, 21])

In [ ]:
a[1,:,1]

array([13, 17, 21])

In [ ]:
a[0,...]

array([1, 2, 3])

In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b=np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

### 3.7고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[1]]

array([1])

In [ ]:
x[[1,1,2,5]]

array([1, 1, 2, 5])

In [ ]:
x[[1,1,2,5,-1,-2,-5,-10]]

array([1, 1, 2, 5, 9, 8, 5, 0])

In [ ]:
x=np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[[5,6]]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[5,6]

np.int64(46)

In [ ]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[[0],[1]]

array([1])

In [ ]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:,[1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[:,[1,2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [ ]:
x[:,[2,1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[ [1,3] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[ [1,3],: ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1],[2] ]

array([10])

In [ ]:
x[ [1,3],[2,2] ]

array([10, 26])

In [ ]:
x[ [1],[2] ]

In [ ]:
x[ [1,3],[2,2,3] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
x[ [1,3],[2] ]

array([10, 26])

In [ ]:
x[ [1],[2] ]

array([10])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0,2,4],1]

array([ 1, 17, 33])

In [ ]:
x[[0,2,4,],:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[[0,2,4,],[0,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a=np.arange(40).reshape(5,8)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
np.arange(2,4)

array([2, 3])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2,4)] [ :, [1,0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,5)] [ :, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
np.arange(-1,-8,-1)

array([-1, -2, -3, -4, -5, -6, -7])

In [ ]:
a[np.arange(2,5)] [:,np.arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])