<a href="https://colab.research.google.com/github/naugim26/2026-BDA/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4주차
# 다차원 배열 결합과 분리

### 4.1 배열결합

In [ ]:
#np.vstack()
import numpy as np
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
#np.vstack 수평으로 결합
x=np.array([1,2,3])
y=np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
np.hstack((np.arange(3),np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.column_stack == np.hstack

False

In [ ]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_2245/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c),axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z=np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x,y),axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
np.stack((a,b))

In [ ]:
np.stack((a,b),axis=1)

In [ ]:
np.stack((a,b),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.arange(1,19).reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [5]:
import numpy as np
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
y  = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [8]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [9]:
ax1 = np.stack((x,y,z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [10]:
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [11]:
ax1.shape

(2, 3, 3)

In [12]:
ax2 = np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [13]:
ax2.shape

(2, 3, 3)

In [14]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [15]:
print('np.stack((x,y,z), axis=0)')
print(np.stack((x,y,z), axis=0))
print('np.stack((x,y,z), axis=1)')
print(np.stack((x,y,z), axis=1))
print('np.stack((x,y,z), axis=2)')
print(np.stack((x,y,z), axis=2))

np.stack((x,y,z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x,y,z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x,y,z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [ ]:
ax0 = np.stack((x,y,z),axis = 0)
ax0

array([[[10, 11, 12],
        [13, 14, 15]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [16]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [18]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [21]:
np.stack((x,y,z),axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [19]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [20]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [22]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [23]:
np.expand_dims(x,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [24]:
np.expand_dims(y,axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [25]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
ax0.shape

(3, 2, 3)

In [ ]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
c = np.arange(1,6,2)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [26]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [29]:
np.row_stack((a,b))

/tmp/ipykernel_1951/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [30]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [31]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

result = np.c_[a,b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
np.r_['-1,2,0',a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
c[:,None]


array([[1],
       [3],
       [5]])

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.c_[a,b], np.column_stack((a,b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [36]:
# np.c_[]와 np.column_stack()
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [37]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [38]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [39]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [40]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [42]:
#np.r_[]개요
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [43]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [44]:
np.row_stack((a,b))

/tmp/ipykernel_1951/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [46]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [47]:
np.r_[-1:1:6j,[0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [48]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [49]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [51]:
np.r_['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [52]:
np.r_['-1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [53]:
np.r_['1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 4.2 배열분리

In [ ]:
import numpy as np
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.splt(y,[2,3,4,6])

AttributeError: module 'numpy' has no attribute 'splt'

In [ ]:
x=np.arange(1,10)
x

In [ ]:
np.split(x,[2,6])

[array([0., 1.]), array([2., 3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a,3,axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a,4,axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

### 4.3 numpy의 난수와 다양한 함수

In [ ]:
#난수 기초
import numpy as np
rg=np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7980E841ECE0

In [ ]:
import numpy as np
rg=np.random.default_rng(1)
rg

Generator(PCG64) at 0x7980E841EEA0

In [ ]:
rg=np.random.default_rng(1)
rg.random()

0.5118216247002567

In [ ]:
#난수 제너레이터의 함수 random()
r=rg.random()
r

0.9699254132161326

In [ ]:
rg.random(5)

array([0.47190972, 0.27404839, 0.00709183, 0.6457209 , 0.71990938])

In [ ]:
rg.random((4,3))

array([[0.59294102, 0.26009745, 0.83988152],
       [0.50949588, 0.51088888, 0.75303021],
       [0.14792204, 0.81962672, 0.68328691],
       [0.78709694, 0.19161626, 0.80236416]])

In [ ]:
from numpy import random
random.random()

0.19485861443983254

In [ ]:
np.random.randint(1,10,15)

array([5, 1, 9, 5, 3, 4, 8, 5, 9, 2, 2, 6, 1, 3, 8])

In [ ]:
np.random.rand(3,4)

array([[0.25361427, 0.60940105, 0.6215122 , 0.37827387],
       [0.65473537, 0.43582507, 0.84385003, 0.89795489],
       [0.44567176, 0.92390663, 0.03800943, 0.50221784]])

In [ ]:
rg=np.random.default_rng(12345)
r= rg.integers(low=0,high=10,size=(3)) #키워드인자
r

array([6, 2, 7])

In [ ]:
rg=np.random.default_rng(12345)
r= rg.integers(1,7,(3,4)) # 1에서 부터 7까지 정수난수 3행 4열
r

array([[5, 2, 5, 2],
       [2, 5, 4, 5],
       [6, 3, 6, 2]])

In [ ]:
r= rg.integers(1,10,(2,8)) # 위치 인자
r

array([[8, 8, 6, 6, 3, 9, 6, 7],
       [7, 8, 7, 9, 5, 5, 3, 9]])

In [ ]:
rg=np.random.default_rng(12)
rg.standard_normal(10) # 표준 정규 분포 실수난수
r

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [ ]:
rg.standard_normal((3,4))

array([[-0.39106572, -1.9302875 , -0.34765362,  0.55145542],
       [-0.38011041,  0.43896931,  0.97954037, -0.54411342],
       [ 1.23135175,  1.62180446,  1.07904594,  1.16546284]])

In [ ]:
rg.standard_normal((10,5))

array([[ 0.25349765,  1.60976993,  0.46272224,  0.65887928,  1.3751745 ],
       [ 2.2381625 ,  0.14958343, -0.48889962,  0.04209808, -0.36115333],
       [-1.23593712, -0.05227152, -0.84882752,  1.31677587, -0.0272043 ],
       [-2.48473122, -0.94491907,  0.42304566, -0.5237312 , -0.76648696],
       [-0.52154314, -0.81124356,  0.60220431, -0.46174811, -0.90976075],
       [ 0.81499179, -1.18249903,  0.19631015, -1.01528571, -0.45287076],
       [-0.52691295, -1.1582476 , -0.62584641,  1.40922899, -1.15209739],
       [ 1.92332707,  0.76801974,  1.5047711 , -0.53412243,  1.02670011],
       [ 0.1577251 ,  1.98288723, -0.46955878,  1.19527939, -0.62811035],
       [ 1.35711925, -0.40312181, -1.14846029, -1.40408915, -0.62047615]])

### NumPy 배열 결합 함수 요약

| 함수명 | 설명 | 축 (Axis) | 특징 |
|:---:|:---|:---:|:---|
| **vstack** | 수직(Vertical) 방향 결합 | axis=0 | 배열을 아래로 쌓음 (행 추가) |
| **hstack** | 수평(Horizontal) 방향 결합 | axis=1 | 배열을 옆으로 붙임 (열 추가) |
| **row_stack** | 행(Row) 방향 결합 | axis=0 | vstack과 동일한 동작 (Alias) |
| **column_stack** | 열(Column) 방향 결합 | axis=1 | 1차원 배열을 열 벡터로 변환하여 결합 |

---

### 💡 핵심 차이점 (1차원 배열 처리)

* **hstack([a, b])**: 1D 배열을 단순 연결하여 **1차원** 결과 반환
* **column_stack([a, b])**: 1D 배열을 각각의 열로 취급하여 **2차원** 결과 반환

In [ ]:
x=np.arange(1,4)
y=np.arange(4,7)
x,y

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(7,13).reshape(2,3)
x,y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [ ]:
np.vstack((a,b)) # 1D -> 2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a,b)) # 1D -> 2D

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack((x,y)) # 2D -> 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((x,y)) # 2D -> 2D

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.column_stack((a,b)) # 1D -> 2D

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a,b)), np.c_[a,b] # 1D -> 2D

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.column_stack((x,y)), np.c_[x,y] # 2D -> 2D

(array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [ ]:
m = np.arange(24).reshape(2, 3, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [ ]:
np.split(n, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]]),
 array([[[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83],
         [84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]

In [ ]:
np.split(n, 2)[1].shape

(2, 4, 6)

In [ ]:
np.split(n, 2, axis=1)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]],
 
        [[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83]]]),
 array([[[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]],
 
        [[60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]